function [VarName1, VarName2, VarName3, VarName4, VarName5] = fcn_Excelimport(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  [VARNAME1, VARNAME2, VARNAME3, VARNAME4, VARNAME5] = IMPORTFILE(FILE)
%  reads data from the first worksheet in the Microsoft Excel
%  spreadsheet file named FILE.  Returns the data as column vectors.
%
%  [VARNAME1, VARNAME2, VARNAME3, VARNAME4, VARNAME5] = IMPORTFILE(FILE,
%  SHEET) reads from the specified worksheet.
%
%  [VARNAME1, VARNAME2, VARNAME3, VARNAME4, VARNAME5] = IMPORTFILE(FILE,
%  SHEET, DATALINES) reads from the specified worksheet for the
%  specified row interval(s). Specify DATALINES as a positive scalar
%  integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [VarName1, VarName2, VarName3, VarName4, VarName5] = importfile("D:\Postdoc\Data\Matlab Analysis\Fly_ID.xlsx", "Sheet1", [1, 5]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2021 12:46:11

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 111];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":E" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5"];
opts.VariableTypes = ["string", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":E" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
VarName1 = tbl.VarName1;
VarName2 = tbl.VarName2;
VarName3 = tbl.VarName3;
VarName4 = tbl.VarName4;
VarName5 = tbl.VarName5;
end